export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOB_DETAILS_REQUEST = 'FETCH_JOB_DETAILS_REQUEST';
export const FETCH_JOB_DETAILS_SUCCESS = 'FETCH_JOB_DETAILS_SUCCESS';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';